Repository prefragrance/prefragrance-client-migration, pull requests merged in 2022-12, with the labels that each got.

#10 feat: implement login token api
  .env.local
  .gitignore
  package.json
  src/common/api/apiCall.ts
  src/common/api/auth/index.ts
  src/common/constants/path.ts
  src/common/hooks/useAuth.ts
  src/common/hooks/useLocalStorage.ts
  src/common/store/user.ts
  src/common/types/search.ts
  src/common/types/user.ts
  src/components/common/loading-spinner/LoadingSpinner.tsx
  src/components/common/searchBar/SearchBar.tsx
  src/components/layout/Navbar.tsx
  src/components/login/useLogin.ts
  src/pages/_app.tsx
  src/pages/login/index.tsx
  src/styles/textComponents.ts
  yarn.lock
Labels: enhancement, settings

#12 feat: add register page ui and integrate api
  src/common/api/auth/index.ts
  src/common/store/user.ts
  src/common/types/user.ts
  src/components/common/button/Button.tsx
  src/components/common/check-box/CheckBox.tsx
  src/components/common/index.ts
  src/components/common/input/Input.tsx
  src/components/common/searchBar/searchModal/index.tsx
  src/components/common/searchBar/useSearch.ts
  src/components/common/select/Select.tsx
  src/components/common/stacks/VStack.tsx
  src/components/register/Done.tsx
  src/components/register/Step.tsx
  src/components/register/Terms.tsx
  src/components/register/UserInfo.tsx
  src/components/register/useRegister.ts
  src/components/search-result/SelectTab/index.tsx
  src/pages/register/index.tsx
  src/pages/search-result/index.tsx
Labels: enhancement

#16 Feat: implement Search result page
  next.config.js
  src/components/common/avatar/Avatar.tsx
  src/components/home/bestReview/review-card/HCard.tsx
  src/components/home/bestReview/review-card/VCard.tsx
  src/components/search-result/SearchResultList/SearchResultBlock.tsx
  src/components/search-result/SearchResultList/index.tsx
  src/pages/magazine-detail/index.tsx
  src/pages/search-result/index.tsx
Labels: enhancement

#19 fix: fix login and register
  public/assets/images/login.png
  src/common/types/user.ts
  src/components/common/button/Button.tsx
  src/components/common/input/Input.tsx
  src/components/login/useLogin.ts
  src/components/register/Terms.tsx
  src/components/register/UserInfo.tsx
  src/components/register/useRegister.ts
  src/pages/login/index.tsx
  src/pages/register/index.tsx
Labels: bug, enhancement

#17 feat: add product detail page
  next.config.js
  src/common/api/product/index.ts
  src/common/constants/colors.ts
  src/common/constants/path.ts
  src/common/types/product.ts
  src/common/utils/calculateSize.ts
  src/components/common/button/Button.tsx
  src/components/common/icon/Icon.tsx
  src/components/common/index.ts
  src/components/common/stacks/HStack.tsx
  src/components/common/stacks/VStack.tsx
  src/components/common/stars/Stars.tsx
  src/components/product/product-info.tsx
  src/components/product/useProductDetail.ts
  src/components/search-result/SearchResultList/SearchResultBlock.tsx
  src/pages/detail/[productDetail]/index.tsx
  src/pages/product/detail/[id].tsx
  src/styles/styles.ts
Labels: enhancement
