Repository prefragrance/prefragrance-client-migration, pull requests merged in 2023-01, with the labels that each got.

#23 feat: add storing q_field and searchText for better UX
  src/common/api/search/index.ts
  src/common/hooks/useLocalStorage.ts
  src/common/store/searchInput.ts
  src/common/types/search.ts
  src/components/common/searchBar/SearchBar.tsx
  src/components/common/searchBar/searchModal/KeywordItem.tsx
  src/components/common/searchBar/searchModal/KeywordList.tsx
  src/components/common/searchBar/searchModal/index.tsx
  src/components/common/searchBar/useRecentSearch.ts
  src/components/common/searchBar/useSearch.ts
  src/components/search-result/SearchResultList/index.tsx
  src/pages/search-result/index.tsx
Labels: enhancement

#24 feat: detail review markup and api integration
  package.json
  src/common/api/product/index.ts
  src/common/hooks/useCommonModal.ts
  src/common/types/product.ts
  src/common/utils/formatDate.ts
  src/components/common/avatar/Avatar.tsx
  src/components/common/index.ts
  src/components/common/modal/Modal.tsx
  src/components/product/product-rate.tsx
  src/components/product/product-review.tsx
  src/components/product/useProductReview.ts
  src/components/search-result/SearchResultList/SearchResultBlock.tsx
  src/pages/login/index.tsx
  src/pages/product/detail/[id].tsx
  src/styles/styles.ts
  yarn.lock
Labels: bug, enhancement, wip

#26 feat: add review modal markup and logic
  src/common/api/apiCall.ts
  src/common/api/authApiCall.ts
  src/common/api/product/index.ts
  src/common/types/product.ts
  src/components/common/button/Button.tsx
  src/components/common/icon/Icon.tsx
  src/components/common/index.ts
  src/components/common/modal/Modal.tsx
  src/components/common/radio-group/RadioGroup.tsx
  src/components/common/searchBar/useSearch.ts
  src/components/common/stars/StarInput.tsx
  src/components/common/stars/Stars.tsx
  src/components/common/textarea/Textarea.tsx
  src/components/product/outlined-icon.tsx
  src/components/product/product-info.tsx
  src/components/product/product-rate.tsx
  src/components/product/review/product-review.tsx
  src/components/product/review/review-modal.tsx
  src/components/product/review/season.tsx
  src/components/product/review/tags-select-box.tsx
  src/components/product/review/time.tsx
  src/components/product/usePostReview.tsx
  src/pages/product/detail/[id].tsx
  src/pages/search-result/index.tsx
Labels: enhancement

#27 chore: disable refetch when window focused
  src/pages/_app.tsx
Labels: bug, enhancement

#31 feat: implement product hot section
  src/common/api/product/index.ts
  src/common/types/product.ts
  src/common/types/search.ts
  src/common/utils/useScrollRestoration.ts
  src/components/common/loading-spinner/LoadingSpinner.tsx
  src/components/common/searchBar/useSearch.ts
  src/components/home/recommendation/InfoBox.tsx
  src/components/home/recommendation/index.tsx
  src/components/home/recommendation/useProductHot.ts
Labels: enhancement
